#!/usr/bin/env bash
#############################################
 if [[ ! -d "${HOME}/qemu_vms" ]]; then
     mkdir "${HOME}/qemu_vms"
 fi

QEMU_GUIDE_DIR=/usr/bin
QEMU_GUIDE_TIPS_01="qemuguide"
QEMU_GUIDE_TIPS_00="Welcome to qemu guide manager v2.0,type ${QEMU_GUIDE_TIPS_01} to start it."

QEMU_MANAGER_MAIN_OPTION=$(
whiptail --title "Qemu guide manager" \
	--menu "${QEMU_GUIDE_TIPS_00}\nPlease use the touch screen or arrow keys + enter to operate." 0 50 0 \
	"1" "🍀 Create a new virtual machine(๑•̀ㅂ•́)و✧" \
	"2" "🌸 Boot an existing virtual machine" \
	"3" "🌈 Boot a system that is on a physical device" \
	"4" "💔 Remove a virtual machine" \
	"0" "🌚 exit" \
	3>&1 1>&2 2>&3
)
case "${QEMU_MANAGER_MAIN_OPTION}" in
	0 | "") exit 0 ;;
	1)	${QEMU_GUIDE_DIR}/qemuguidecreate ;;
	2)	${QEMU_GUIDE_DIR}/qemubootexisting ;;
	3)	${QEMU_GUIDE_DIR}/qemubootdisk ;;
	4)	${QEMU_GUIDE_DIR}/qemudelete ;;
esac
