#!/bin/bash
cd ~/qemu_vms

menu_options=""

for item in $(ls); do
  menu_options+="$item "
  menu_options+="$item "
done

vm_path=$(whiptail --title "Select a machine" --menu "Select the machine that you want to remove (THIS OPERATION CANNOT BE UNDONE!!!\nThen press Enter if you really want to delete this virtual machine" 20 60 10 \
  $menu_options \
  3>&1 1>&2 2>&3)

vm_name=$(basename "$vm_path")

iso_needed=$(whiptail --yesno "Are You Sure?" 10 60 3>&1 1>&2 2>&3)

if [ $? -eq 0 ]; then
   rm -r $vm_name
   
else 
	exit 0
fi

